### ISSUE TITLE
Import panel resize

### ISSUE THREAD

**Issue by Jhsmit** [SingleMolecule/iSBatch#13]
The import panel does not resize correctly

**Comment by cmpunter** [comment]
The import panel has a minimum size. When resizing this windows below this minimum size all gui components try to shrink so that everything still fits in the window. The result of this is that the input fields will disappear (or at least will be super tiny). I think the solution is to disable resizing on each dialog window.

**Comment by cmpunter** [comment]
When using a null layout the components will not try to shrink. Also in this case some of the components will not (or partly) be visible
